import sys
import json
import csv
import gzip
import importlib
from pathlib import Path

import tqdm
import pandas as pd
import numpy as np
import networkx as nx
import osmnx as ox
import valhalla
from valhalla import Actor
from valhalla.utils import decode_polyline
from valhalla.config import get_config

from imn_generation import clear_tuples4json
from mobility_generation import haversine_distance


def _log(msg: str, verbose: bool = False):
    if verbose:
        print(msg)


def _reload_valhalla(tile_extract: str = "valhalla/valhalla_tiles.tar",
                     tile_dir: str = "valhalla/valhalla_tiles") -> Actor:
    # Ugly way to free memory is to reload everything
    importlib.reload(valhalla)
    importlib.reload(valhalla.config)
    importlib.reload(valhalla.valhalla_build_config)

    config = get_config(tile_extract, tile_dir)
    actor = Actor(config)

    return actor


def _sample_trajectory(df_traj: pd.DataFrame,
                       thresh: float = 1.0) -> pd.DataFrame:
    """
    Undersample the points generated by Valhalla, which are often too dense and
    may cause issues with osmnx. The function preserves all points matched from
    the original trajectory, and reduces the number of interpolated points.

    Parameters
    ----------
    df_traj : pd.DataFrame
        A pandas DataFrame containing the trajectory to be sampled.
    
    thresh : float, optional
        The minimum distance threshold below which to drop interpolated points.
    """
    selected_idx = []
    last_coord = None

    for idx, row in df_traj.iterrows():
        if row['type'] == 'matched':
            selected_idx.append(idx)
            last_coord = (row['latitude'], row['longitude'])
            continue
        if last_coord is None:
            selected_idx.append(idx)
            last_coord = (row['latitude'], row['longitude'])
        else:
            dist = haversine_distance(last_coord[1], last_coord[0], row['longitude'], row['latitude'])
            if dist >= thresh:
                selected_idx.append(idx)
                last_coord = (row['latitude'], row['longitude'])

    return df_traj.loc[selected_idx].copy()


def map_match_valhalla_trajectory(df_traj: pd.DataFrame,
                                  uid: np.int64,
                                  tid: np.int64,
                                  actor: Actor,
                                  writer: csv.DictWriter) -> pd.DataFrame:
    """
    Map-match and reconstruct a trajectory using Valhalla's `trace_attributes`
    action.
    
    Parameters
    ----------
    df_traj : pd.DataFrame
        A pandas DataFrame containing the trajectory to be map-matched, with
        columns 'latitude', 'longitude', 'timestamp'.
    uid : np.int64
        The unique identifier of the user to which the trajectory belongs.
    tid : np.int64
        The unique identifier of the trajectory.
    actor : Actor
        A pyvalhalla Actor initialized with a valid Valhalla configuration.
    writer : csv.DictWriter
        A CSV writer that writes the matched trajectory points.
    """
    df_request = df_traj[['latitude', 'longitude', 'timestamp']].copy()

    # Renaming columns to fit Valhalla's expected input
    df_request.columns = ['lat', 'lon', 'time']
    df_request.reset_index(drop=True, inplace=True)
    coords = df_request.to_dict(orient='records')

    msg = {
        "shape": coords,
        "shape_match": "map_snap",
        "costing": "auto",
        "verbose": True,
        "trace_options.search_radius":100,
        "trace_options.gps_accuracy":50.0,
        "trace_options.breakage_distance":10000,
        "filters": {
            "attributes":["shape","matched.point","matched.type",
            "matched.edge_index","edge.begin_shape_index",
            "edge.end_shape_index"],
            "action":"include"
            },
        "format":"osrm",
    }

    response = actor.trace_attributes(msg)

    matched_pts = response['matched_points']
    df_matched = pd.json_normalize(matched_pts)    
    df_matched['time'] = df_request['time']

    # Decoding the polyline to get the full route
    route = decode_polyline(response['shape'], 6, "latlng")
    df_route = pd.DataFrame(route, columns=['latitude','longitude'])

    df_route['timestamp'] = 0
    df_route['type'] = 'interpolated'
    df_route.at[0,'type'] = 'matched'
    df_route.at[len(df_route)-1,'type'] = 'matched'
    df_route.at[0,'timestamp'] = df_matched.time[0]
    df_route.at[len(df_route)-1,'timestamp'] = df_matched.time[len(df_matched)-1]

    df_matched = df_matched.dropna().reset_index()
    lst_edge = df_matched['edge_index']
    edges = response['edges']
    df_edges = pd.json_normalize(edges)

    for i in range(1, len(lst_edge)-1):
        # Setting type and timestamp for matched input points
        f = lst_edge[i]
        if df_matched['type'][i] != 'matched' or f not in df_edges.index:
            #TODO check why some edges in result do not appear in df_edges
            # Known bug with interpolated pts returns invalid edge id
            continue
        c = df_edges.end_shape_index[f]-1
        df_route.loc[c, 'type'] = 'matched'
        df_route.loc[c, 'timestamp'] = df_matched.time[i]

    # Downsampling shape points to avoid osmnx issues
    df_route = _sample_trajectory(df_route, thresh=750.0)
    
    df_route.drop(columns=['type'], inplace=True)
    df_route['tid'] = tid

    for _, row in df_route.iterrows():
        writer.writerow([uid, tid, row['latitude'], row['longitude'], row['timestamp']])


def map_match_valhalla_all(dict_trajs: dict,
                           output_path: str,
                           tile_extract: str = "valhalla/valhalla_tiles.tar",
                           tile_dir: str = "valhalla/valhalla_tiles",
                           verbose: bool = False) -> list:
    """
    Map-match and reconstruct all the trajectories in the input dictionary
    using Valhalla's `trace_attributes` action.

    Parameters
    ----------
    dict_trajs : dict
        A dictionary mapping each user ID to a pandas DataFrame with columns
        'id', 'latitude', 'longitude', 'timestamp', containing the segmented
        trajectories for that user.
    output_path : str
        The path to the output compressed CSV file where the trajectories will
        be stored.
    tile_dir : str, optional
        The directory where the Valhalla tiles are stored.
    tile_extract : str, optional
        The path to the tar file containing the compressed Valhalla tiles.
    verbose : bool, optional
        Controls whether to display a progress bar during processing.

    Returns
    -------
    rejected : list
        A list of tuples (uid, tid), containing all the trajectories rejected
        by Valhalla during map-matching.
    """
    # TODO parallelize (each worker gets its own Actor instance)
    config = get_config(tile_extract, tile_dir)
    actor = Actor(config)

    _log("Starting Valhalla map-matching", verbose)
    with gzip.open(output_path, 'wt') as fout:
        writer = csv.writer(fout)
        writer.writerow(['uid', 'tid', 'latitude', 'longitude', 'timestamp'])

        rejected = [] # contains trajectories that failed map-matching
        for uid, df_traj in tqdm.tqdm(dict_trajs.items(), desc="Users", file=sys.stdout, disable=not verbose):
            for tid in df_traj['id'].unique():
                try:
                    map_match_valhalla_trajectory(df_traj[df_traj['id'] == tid], uid, tid, actor, writer)
                except RuntimeError:
                    # To avoid a Valhalla segfault
                    actor = _reload_valhalla(tile_extract, tile_dir)
                    rejected.append((int(uid), int(tid)))
                    continue
    _log("Valhalla map-matching completed", verbose)
    return rejected


def points_to_osmnx_routes(G: nx.MultiDiGraph,
                           input_path: str,
                           output_path: str,
                           verbose: bool = False):
    """
    For each user in input_path, match a set of trajectories as sequences of
    points with lat-lon coordinates to an osmnx graph, reconstructing the full
    path. The final path is a sequence of node IDs of the osmnx graph.

    Parameters
    ----------
    G : nx.MultiDiGraph
        The osmnx graph on which to match the trajectory.
    input_path : str
        The path to the compressed csv input file containing the map-matched
        trajectories.
    output_path : str
        The path to the compressed JSON output file where the reconstructed
        routes will be stored.
    verbose : bool, optional
        Controls whether to display a progress bar during processing.
    """
    df_matched = pd.read_csv(input_path, compression='gzip', sep=',')

    routes = {}
    edges = ox.nearest_edges(G, df_matched['longitude'], df_matched['latitude'])

    _log("Starting conversion to osmnx routes", verbose)
    u_idx = 0
    for uid in tqdm.tqdm(df_matched['uid'].unique(), file=sys.stdout, desc="Users", disable=not verbose):
        user_info = {}
        t_idx = u_idx

        df_trajs = df_matched[df_matched['uid'] == uid]
        for tid in df_trajs['tid'].unique():
            n_edges = len(df_trajs[df_trajs['tid'] == tid])
            nodes = []
            nodes.append(edges[t_idx][0]) # First node in the path

            for i, curr_edge in enumerate(edges[t_idx: t_idx + n_edges - 1]):
                next_edge = edges[t_idx + i + 1]
                if curr_edge == next_edge:
                    # Points fall on the same edge, skip
                    continue
                if curr_edge[1] == next_edge[0]:
                    # Points fall onto consecutive edges
                    nodes.append(curr_edge[1])
                else:
                    # Edges are disconnected, find shortest path
                    path = nx.shortest_path(G, curr_edge[1], next_edge[0])
                    nodes.extend(path)
            nodes.append(edges[t_idx + n_edges - 1][1])

            user_info[int(tid)] = {
                'start_timestamp': int(df_trajs[(df_trajs['uid'] == uid) & (df_trajs['tid'] == tid)]['timestamp'].iloc[0]),
                'end_timestamp': int(df_trajs[(df_trajs['uid'] == uid) & (df_trajs['tid'] == tid)]['timestamp'].iloc[-1]),
                'nodes': nodes
            }
            t_idx += n_edges

        routes[int(uid)] = user_info
        u_idx += len(df_trajs)

    _log("Conversion to osmnx routes completed", verbose)
    with gzip.GzipFile(output_path, 'w') as fout:
        fout.write(json.dumps(clear_tuples4json(routes)).encode('utf-8'))


def read_osmnx_routes(filename: str) -> dict:
    """
    Read the osmnx routes computed by `points_to_osmnx_routes` from a
    compressed JSON file.

    Parameters
    ----------
    filename : str
        The path to the input compressed JSON file.

    Returns
    -------
    routes : dict
        A nested dictionary that maps each user ID to its trajectories. Each
        user is its own dictionary that pairs trajectory IDs with the list of
        osmnx graph nodes that compose the full path traversed by the
        trajectory points (`nodes`), along with the timestamps of the start and
        end points of the trajectory (`start_timestamp` and `end_timestamp`).
    """
    with gzip.GzipFile(filename, 'r') as f:
        data = json.load(f)

    routes = {
        int(uid): {
            int(tid): route for tid, route in uid_data.items()
        }
        for uid, uid_data in data.items()
    }

    return routes