import os
import shutil
import json
import numpy as np
import pandas as pd
import networkx as nx
import osmnx as ox
import geopandas as gpd

from tqdm import tqdm
import multiprocessing.pool as mpp
from sklearn.preprocessing import MaxAbsScaler
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import dijkstra

from mobility_distance_functions import spherical_distance

# Global variables for multiprocessing
G_WORKER = None
N_NODES = None
NODE_TO_IDX = None
IDX_TO_NODE = None
U_INDICES = None 
V_INDICES = None
ATTRIBUTE_VALUES = None
COST_ATTRIBUTES = None
BASE_COST = None

# List of edge attributes to consider for user preference learning
attributes = [
    'residential',
    'motorway',
    'length',
    'speed_kph',
    'travel_time',
    'stop_short',
    'stop_medium',
    'stop_long',
    'flow_low',
    'flow_medium',
    'flow_high',
    'water',
    'landuse_green',
    'landuse_commercial',
    'landuse_residential',
    'landuse_industrial'
]


# -------------- Utils -------------- #


def _init_global_variables(G = None,
                           n_nodes = None,
                           node_to_idx = None,
                           idx_to_node = None,
                           u_indices = None,
                           v_indices = None,
                           attribute_values = None,
                           cost_attributes = None,
                           base_cost = None):
    """Initialize global variables for multiprocessing workers."""
    global G_WORKER, N_NODES, NODE_TO_IDX, IDX_TO_NODE, U_INDICES, V_INDICES
    global ATTRIBUTE_VALUES, COST_ATTRIBUTES, BASE_COST

    G_WORKER = G
    N_NODES = n_nodes
    NODE_TO_IDX = node_to_idx
    IDX_TO_NODE = idx_to_node
    U_INDICES = u_indices
    V_INDICES = v_indices
    ATTRIBUTE_VALUES = attribute_values
    COST_ATTRIBUTES = cost_attributes
    BASE_COST = base_cost


def _istarmap(self, func, iterable, chunksize=1):
    """starmap-version of imap"""
    self._check_running()
    if chunksize < 1:
        raise ValueError(
            "Chunksize must be 1+, not {0:n}".format(
                chunksize))

    task_batches = mpp.Pool._get_tasks(func, iterable, chunksize)
    result = mpp.IMapIterator(self)
    self._taskqueue.put(
        (
            self._guarded_task_generation(result._job,
                                          mpp.starmapstar,
                                          task_batches),
            result._set_length
        ))
    return (item for chunk in result for item in chunk)


def _log(msg: str, verbose: bool = False):
    if verbose:
        print(msg)


def _get_path(predecessors, source_idx, target_idx):
    """Return the path generated by SciPy's Dijkstra"""
    path = []
    current = target_idx

    while current != -9999 and current != source_idx:
        path.append(current)
        current = predecessors[current]
        
    if current == source_idx:
        path.append(source_idx)
        return path[::-1]
    
    return None


def _worker_compare_fastest(uid: int, user_routes: dict):
    """
    Worker function to compare the real routes with the corresponding
    fastest routes of a specific user.
    
    Parameters
    ----------
    uid : int
        The user ID.
    user_routes : dict
        A dictionary that pairs trajectory IDs to a dictionary containing the
        list of osmnx graph nodes that compose the full path traversed by the
        trajectory points (`nodes`), along with the timestamps of the start and
        end points of the trajectory (`start_timestamp` and `end_timestamp`).

    Returns
    -------
    uid: int
        The user ID (to reidentify the user in the main process).
    real_stats : dict
        A dictionary containing the aggregated edge attributes for the real
        user routes (mean, median, 1st and 3rd quartiles, necessary to find
        clusters among user preferences).
    fastest_means : dict
        A dictionary containing the mean edge attributes for the fastest
        routes.
    alphas: dict
        A dictionary containing the ratios between the real and fastest mean
        edge attributes for the user.
    """
    adj_matrix = coo_matrix(
            (ATTRIBUTE_VALUES, (U_INDICES, V_INDICES)),
            shape=(N_NODES, N_NODES)
        )
    real_attributes = {attr: [] for attr in attributes}
    fastest_attributes = {attr: [] for attr in attributes}

    # Collecting all origin-destination pairs for the user
    orig_indices = []
    dest_indices = []
    for _, route_data in user_routes.items():
        route = route_data['nodes']
        origin = (G_WORKER.nodes[route[0]]['x'], G_WORKER.nodes[route[0]]['y'])
        destination = (G_WORKER.nodes[route[-1]]['x'], G_WORKER.nodes[route[-1]]['y'])
        if spherical_distance(origin, destination) < 500:
            continue
        
        orig_idx = NODE_TO_IDX[route[0]]
        dest_idx = NODE_TO_IDX[route[-1]]
        orig_indices.append(orig_idx)
        dest_indices.append(dest_idx)

        # Collecting real attributes
        for node1, node2 in zip(route, route[1:]):
            data = G_WORKER.get_edge_data(node1, node2, 0)
            for attr in attributes:
                value = data.get(attr, 0)
                real_attributes[attr].append(float(value))

    _, predecessors = dijkstra(
        adj_matrix,
        directed=True,
        indices=orig_indices,
        return_predecessors=True
    )

    # Collecting fastest attributes
    for i, (orig_idx, dest_idx) in enumerate(zip(orig_indices, dest_indices)):
        path_indices = _get_path(predecessors[i], orig_idx, dest_idx)
        opt_route = [IDX_TO_NODE[i] for i in path_indices]
        for node1, node2 in zip(opt_route, opt_route[1:]):
            data = G_WORKER.get_edge_data(node1, node2, 0)

            for attr in attributes:
                value = data.get(attr, 0)
                fastest_attributes[attr].append(np.float64(value))

    alphas = {}
    real_stats = {'uid': []}
    real_stats.update({f'{attr}_{stat}': [] for attr in attributes for stat in ['mean', 'median', 'percentile_25', 'percentile_75']})

    fastest_means = {'uid': []}
    fastest_means.update({attr: [] for attr in attributes})

    for attr in attributes:
        real_stats[f'{attr}_mean'] = np.nanmean(real_attributes[attr])
        real_stats[f'{attr}_median'] = np.nanmedian(real_attributes[attr])
        real_stats[f'{attr}_percentile_25'] = np.nanpercentile(real_attributes[attr], 25)
        real_stats[f'{attr}_percentile_75'] = np.nanpercentile(real_attributes[attr], 75)

        fastest_means[attr] = np.nanmean(fastest_attributes[attr])

        if fastest_means[attr] > 0:
            ratio = np.float64(real_stats[f'{attr}_mean']) / np.float64(fastest_means[attr])
        elif real_stats[f'{attr}_mean'] == 0:
            ratio = np.float64(1.0) # Both are equal to 0
        else:
            ratio = np.float64(10.0) # Upper bound

        alphas[attr] = ratio

    return uid, real_stats, fastest_means, alphas


def compare_fastest(G: nx.MultiDiGraph,
                    user_routes: dict,
                    real_path: str,
                    fastest_path: str,
                    alphas_path: str,
                    num_processes: int = None,
                    verbose: bool = False):
    """
    Compare the real user routes with the corresponding fastest routes,
    computing the mean of edge attributes for each user for both real and
    fastest routes, and the ratio between them.

    Parameters
    ----------
    G : nx.MultiDiGraph
        The osmnx graph, preprocessed with `add_edge_attributes`.
    user_routes : dict
        A nested dictionary that maps each user ID to its trajectories. Each
        user is its own dictionary that pairs trajectory IDs with the list of
        osmnx graph nodes that compose the full path traversed by the
        trajectory points (`nodes`), along with the timestamps of the start and
        end points of the trajectory (`start_timestamp` and `end_timestamp`).
    real_path : str
        Path to save the CSV file containing the aggregated edge attributes for
        the real user routes (mean, median, 1st and 3rd quartiles).
    fastest_path : str
        Path to save the CSV file containing the mean edge attributes for the
        fastest routes.
    alphas_path : str
        Path to save the JSON file containing the ratios between the real and
        fastest mean edge attributes for each user.
    num_processes : int, optional
        Number of processes to use for parallel computation. If None, the
        number of CPU cores will be used. Defaults to None.
    verbose : bool, optional
        Whether to print progress messages. Defaults to False.
    """
    
    # Conversion to indices/matrix format for scipy
    nodes = list(G.nodes())
    n_nodes = len(G.nodes)
    node_to_idx = {node: i for i, node in enumerate(nodes)}
    idx_to_node = {i: node for i, node in enumerate(nodes)}

    edges = list(G.edges(data=True))
    u_indices = np.array([node_to_idx[u] for u, _, _ in edges])
    v_indices = np.array([node_to_idx[v] for _, v, _ in edges])

    travel_time_values = np.array([d['travel_time'] for _, _, d in edges])

    mpp.Pool.istarmap = _istarmap
    pool = mpp.Pool(processes=num_processes,
                    initializer=_init_global_variables,
                    initargs=(G,
                              n_nodes,
                              node_to_idx,
                              idx_to_node,
                              u_indices,
                              v_indices,
                              travel_time_values)
    )

    alphas = {}

    real_stats = {'uid': []}
    real_stats.update({f'{attr}_{stat}': [] for attr in attributes for stat in ['mean', 'median', 'percentile_25', 'percentile_75']})

    fastest_means = {'uid': []}
    fastest_means.update({attr: [] for attr in attributes})

    for user_result in list(tqdm(pool.istarmap(_worker_compare_fastest, [(uid, user_routes) for uid, user_routes in user_routes.items()]),
                                 desc='Users',
                                 total=len(user_routes),
                                 disable=not verbose)):
        uid = user_result[0]
        real_stats_user = user_result[1]
        fastest_means_user = user_result[2]
        alphas_user = user_result[3]

        alphas[user_result[0]] = {attr: alphas_user[attr] for attr in attributes}

        real_stats['uid'].append(uid)
        fastest_means['uid'].append(uid)
        for attr in attributes:
            real_stats[f'{attr}_mean'].append(real_stats_user[f'{attr}_mean'])
            real_stats[f'{attr}_median'].append(real_stats_user[f'{attr}_median'])
            real_stats[f'{attr}_percentile_25'].append(real_stats_user[f'{attr}_percentile_25'])
            real_stats[f'{attr}_percentile_75'].append(real_stats_user[f'{attr}_percentile_75'])

            fastest_means[attr].append(fastest_means_user[attr])

    pd.DataFrame(real_stats).to_csv(real_path,index=False)
    pd.DataFrame(fastest_means).to_csv(fastest_path, index=False)

    with open(alphas_path, 'w') as f:
        json.dump(alphas, f)


def _worker_compute_user_gaps(uid: int,
                             user_routes: dict,
                             real_user_means: np.ndarray,
                             candidate_beta: float,
                             c_idx: int,
                             it: int,
                             user_alphas: dict,
                             betas: dict) -> tuple[np.ndarray, list[list[int, int, float]]]:
    """
    Calculate the user-adjusted routes according to the given beta and alpha
    values, and return the relative gap between the means of the attributes for
    the real and adjusted routes of the user.

    Parameters
    ----------
    uid : int
        The user ID.
    user_routes : dict
        A dictionary that pairs the user's trajectory IDs to a dictionary
        containing the list of osmnx graph nodes that compose the full path
        traversed by the trajectory points (`nodes`).
    real_user_means : np.ndarray
        A 1D array containing the mean values of the attributes for the user's
        real routes.
    candidate_beta : float
        The beta value to test for the cost attribute being tested in the
        current iteration.
    c_idx : int
        The index of the cost attribute being tested in the current iteration.
    it : int
        The current sub-iteration number across all cost attributes, used to
        determine which cost attributes to include in the user-specific cost
        function according to the iteration schedule.
    user_alphas : dict
        A dictionary mapping each attribute to the alpha ratio for the user.
    betas : dict
        A dictionary mapping each cost attribute to its current beta value.

    Returns
    -------
    gap : np.ndarray
        A 1D array containing the relative gap between the means of the
        attributes for the real and adjusted routes of the user.
    overlaps : list[list[int, int, float]]
        A list of lists, each containing the user ID, trajectory ID and overlap
        between the real and adjusted route for each trajectory of the user.
    """
    adjusted_means = {}

    # Compute user-specific edge costs
    user_costs = ATTRIBUTE_VALUES[attributes.index('travel_time')].copy()
    for attr in COST_ATTRIBUTES[:it+1]:
        w = (np.exp(1 - user_alphas[attr]) - 1)

        if candidate_beta is not None:
            b = candidate_beta if attr == COST_ATTRIBUTES[c_idx] else betas[attr]
        else:
            # During random search
            b = betas[attr]

        user_costs += b * w * ATTRIBUTE_VALUES[attributes.index(attr)]
    user_costs = BASE_COST * (1 + user_costs)
    user_costs[user_costs <= 0] = 0.01 * BASE_COST

    adj_matrix = coo_matrix((user_costs, (U_INDICES, V_INDICES)), shape=(N_NODES, N_NODES))

    # Collecting all origin-destination pairs for the user, so paths can be computed all at once
    orig_indices = []
    dest_indices = []
    tids = [] # Track which routes are actually used
    for tid, route_data in user_routes.items():
        route = route_data['nodes']

        origin = (G_WORKER.nodes[route[0]]['x'], G_WORKER.nodes[route[0]]['y'])
        destination = (G_WORKER.nodes[route[-1]]['x'], G_WORKER.nodes[route[-1]]['y'])
        if spherical_distance(origin, destination) < 500:
            # Route starts and stops near the same point
            continue
        
        tids.append(tid)

        orig_idx = NODE_TO_IDX[route[0]]
        dest_idx = NODE_TO_IDX[route[-1]]

        orig_indices.append(orig_idx)
        dest_indices.append(dest_idx)

    if len(orig_indices) == 0:
        return None, None

    _, predecessors = dijkstra(
        adj_matrix,
        directed=True,
        indices=orig_indices,
        return_predecessors=True
    )

    # Recording edge attributes for the newly computed paths
    opt_routes = []
    for i, (orig_idx, dest_idx) in enumerate(zip(orig_indices, dest_indices)):
        path_indices = _get_path(predecessors[i], orig_idx, dest_idx)
        opt_route = [IDX_TO_NODE[i] for i in path_indices]
        opt_routes.append(opt_route)

        for node1, node2 in zip(opt_route, opt_route[1:]):
            data = G_WORKER.get_edge_data(node1, node2, 0)

            for attr in attributes:
                value = data.get(attr, np.nan)
                if attr not in adjusted_means: adjusted_means[attr] = []
                adjusted_means[attr].append(float(value))

    adjusted_means = np.array([np.nanmean(adjusted_means[attr]) for attr in attributes])

    # Computing the relative gap of the means for the user
    gap = np.where(
        adjusted_means != 0,
        (real_user_means - adjusted_means) / adjusted_means,
        np.where(real_user_means == 0,
                 0.0, # Both are equal to 0
                 np.nan
        )
    )

    # Computing overlap between real and adjusted routes
    overlaps = []
    for i, tid in enumerate(tids):
        real_edges = set(user_routes[tid]['nodes'])
        adj_edges = set(opt_routes[i])

        common_nodes = real_edges.intersection(adj_edges)
        overlap = len(common_nodes) / max(len(real_edges), len(adj_edges))
        overlaps.append([uid, tid, overlap])

    return gap, overlaps


def _random_search(pool: mpp.Pool, 
                   cost_attributes: list,
                   real_means: pd.DataFrame,
                   routes: dict,
                   alphas: dict,
                   verbose: bool = False):
    # Random search for starting betas of learn_user_preferences
    betas_rs = [0.1, 0.5, 0.25, 1.0, 2.5, 5.0, 10.0]
    combinations = set()
    while len(combinations) < 16:
        combination = tuple(np.random.choice(betas_rs, size=len(cost_attributes)))
        combinations.add(combination)

    best_mae = np.array([np.inf] * len(attributes))
    best_combo = None
    for combination in tqdm(combinations, desc='Random search combinations', disable=not verbose):
        _log(f"Testing combination: {[float(b) for b in combination]}", verbose)

        user_results = list(
            tqdm(pool.istarmap(_worker_compute_user_gaps,
                            [(uid,
                              user_routes,
                              real_means[real_means['uid'] == uid][attributes].values[0],
                              None,
                              None,
                              4,
                              alphas[str(uid)],
                              {cost: combination[i] for i, cost in enumerate(cost_attributes)})
                              for uid, user_routes in routes.items()]),
                desc='Users',
                total=len(routes),
                disable=not verbose)
        )

        gaps = []
        for gap, _ in user_results:
            gaps.append(gap)
        gaps = np.array(gaps)

        mae_by_attr = np.nanmean(np.abs(gaps), axis=0)
        if (mae_by_attr < best_mae).all():
            best_mae = mae_by_attr
            best_combo = combination

    _log(f"Best combination from random search: {best_combo}, MAE: {best_mae}", verbose)

    betas = {
        cost: best_combo[i] for i, cost in enumerate(cost_attributes)
    }

    return betas


def _search_betas(pool: mpp.Pool,
                  routes: list,
                  cost_attributes: list,
                  alphas: dict,
                  betas: dict,
                  real_means: pd.DataFrame,
                  results_dir: str,
                  iterations: int,
                  verbose: bool = False):
    # Search for the best betas for the given routes, starting from the provided betas

    # List of MAE values across all sub-iterations
    mae = []
    best_maes = {attr: np.inf for attr in cost_attributes}

    for i in range(iterations * len(cost_attributes)):
        c_idx = i % len(cost_attributes) # index in cost_attributes
        a_idx = attributes.index(cost_attributes[c_idx]) # index in attributes
        
        _log(f"It {i // len(cost_attributes)}, adjusting attribute {cost_attributes[c_idx]}", verbose)

        c_beta = betas[cost_attributes[c_idx]]
        beta_gaps = {} # Collects gaps for all users for each candidate beta
        beta_overlaps = {} # Collects overlaps for all users for each candidate beta

        for candidate_beta in [c_beta/10, c_beta/2, c_beta, c_beta*10/2, c_beta*10]:
            _log(f"Testing beta {candidate_beta}", verbose)

            user_results = list(
                tqdm(pool.istarmap(_worker_compute_user_gaps,
                                [(uid,
                                    user_routes,
                                    real_means[real_means['uid'] == uid][attributes].values[0],
                                    candidate_beta,
                                    c_idx,
                                    i,
                                    alphas[str(uid)],
                                    betas) 
                                    for uid, user_routes in routes.items()]),
                    desc='Users',
                    total=len(routes),
                    disable=not verbose)
            )
            beta_gaps[candidate_beta] = []
            beta_overlaps[candidate_beta] = []
            for gap, overlaps in user_results:
                beta_gaps[candidate_beta].append(gap)
                beta_overlaps[candidate_beta].extend(overlaps)

        # Checking if any beta improves the MAE for the current cost attribute
        best_gaps = None
        best_overlap = None
        for b, g in beta_gaps.items():
            g = np.array(g)
            b_mae = np.nanmean(np.abs(g[:,a_idx]))

            if b_mae < best_maes[cost_attributes[c_idx]]:
                # Improvement
                best_maes[cost_attributes[c_idx]] = b_mae
                betas[cost_attributes[c_idx]] = b
                best_gaps = g
                best_overlap = beta_overlaps[b]

        if best_gaps is None:
            # No improvement found
            _log(f"No improvement found for attribute  {cost_attributes[c_idx]}", verbose)
        else:
            _log(f"Found improvement for attribute {cost_attributes[c_idx]}: {betas[cost_attributes[c_idx]]}, MAE: {best_maes[cost_attributes[c_idx]]}", verbose)

            # Saving intermediate relative gaps
            pd.DataFrame(best_gaps, columns=attributes).to_csv(os.path.join(results_dir, f'gaps_iter_{i}.csv'), index=False)
        
            # Saving intermediate overlaps
            pd.DataFrame(best_overlap, columns=['uid', 'tid', 'overlap']).to_csv(os.path.join(results_dir, f'overlaps_iter_{i}.csv'), index=False)
            _log('Mean Overlap: {:.4f}'.format(np.mean(best_overlap, axis=0)[2]), verbose)
            
            # Saving current beta values
            json.dump(betas, open(os.path.join(results_dir, f'betas_iter_{i}.json'), 'w'))

        mae.append(best_maes[cost_attributes[c_idx]])

    _log(f"Learned betas: {betas}", verbose)

    json.dump(betas, open(os.path.join(results_dir, f'learned_betas.json'), 'w'))
    np.save(os.path.join(results_dir, f'mae.npy'), np.array(mae))    


def learn_user_preferences(G: nx.MultiDiGraph,
                           routes: list,
                           cost_attributes: list,
                           alphas_path: str,
                           real_path: str,
                           results_dir: str,
                           iterations: int,
                           cluster_to_uid: dict = None,
                           num_processes: int = None,
                           verbose: bool = False):
    """
    Iteratively learn user preferences for the cost attributes by adjusting the
    global beta values for each cost attribute. At each iteration, if a
    candidate beta value is found to improve the relative gap for the current
    cost attribute, the beta is updated and the improvement is kept. Otherwise,
    the beta is kept unchanged, and the next iteration continues by testing
    adjustments to the next cost attribute.

    Parameters
    ----------
    G : nx.MultiDiGraph
        The osmnx graph, preprocessed with `add_edge_attributes`.
    routes : dict
        A nested dictionary that maps each user ID to its trajectories. Each
        user is its own dictionary that pairs trajectory IDs with the list of
        osmnx graph nodes that compose the full path traversed by the
        trajectory points (`nodes`), along with the timestamps of the start and
        end points of the trajectory (`start_timestamp` and `end_timestamp`).
    cost_attributes : list
        The list of edge attributes to use in the cost function that generates
        the user-adjusted routes.
    iterations: int
        The number of iterations to perform for each cost attribute. Each
        iteration tests a set of candidate beta values for each of the
        attributes in `cost_attributes`, and updates the beta values according
        to the results.
    cluster_to_uid : dict, optional
        A dictionary that maps each cluster index to the list of user IDs that
        belong to that cluster. If None, all users are treated as a single 
        cluster. If provided, a unique set of beta values will be computed for
        each cluster.
    num_processes : int, optional
        Number of processes to use for parallel computation. If None, the
        number of CPU cores will be used. Defaults to None.
    verbose : bool, optional
        Whether to print progress messages/bars. Defaults to False.
    """
    # TODO replace paths with actual dataframes/dicts

    # Creating folder for results
    if os.path.exists(results_dir):
        _log(f"Warning: results directory {results_dir} already exists. It will be overwritten.", verbose)
        shutil.rmtree(results_dir)
    os.makedirs(results_dir)
    
    # Conversion to indices/matrix format for scipy
    nodes = list(G.nodes())
    n_nodes = len(G.nodes)
    node_to_idx = {node: i for i, node in enumerate(nodes)}
    idx_to_node = {i: node for i, node in enumerate(nodes)}

    edges = list(G.edges(data=True))
    u_indices = np.array([node_to_idx[u] for u, _, _ in edges])
    v_indices = np.array([node_to_idx[v] for _, v, _ in edges])

    attribute_values = []
    for attr in attributes:
        attribute_values.append(np.array([float(d[attr]) for _, _, d in edges]))
    attribute_values = np.array(attribute_values)

    base_cost = np.nanmedian(attribute_values[attributes.index('travel_time')])
    scaler = MaxAbsScaler()
    attribute_values = scaler.fit_transform(attribute_values)

    real_means = pd.read_csv(real_path)[['uid'] + [f'{attr}_mean' for attr in attributes]]
    real_means.columns = ['uid'] + attributes

    alphas = json.load(open(alphas_path, 'r'))

    # Patching multiprocessing to allow starmap + tqdm progress bar
    mpp.Pool.istarmap = _istarmap
    pool = mpp.Pool(processes=num_processes,
                    initializer=_init_global_variables,
                    initargs=(G,
                              n_nodes,
                              node_to_idx,
                              idx_to_node,
                              u_indices,
                              v_indices,
                              attribute_values,
                              cost_attributes,
                              base_cost)
    )

    if cluster_to_uid is None:
        _log("Searching initial betas", verbose)
        betas = _random_search(pool, cost_attributes, real_means, routes, alphas, verbose)
        results_subdir = results_dir
    else:
        for cluster, cluster_uids in cluster_to_uid.items():
            _log(f"Searching initial betas for cluster {cluster}", verbose)
            os.makedirs(os.path.join(results_dir, f"cluster_{cluster}"))

            cluster_routes = {uid: routes[uid] for uid in cluster_uids}
            betas = _random_search(pool, cost_attributes, real_means, cluster_routes, alphas, verbose)

            results_subdir = os.path.join(results_dir, f"cluster_{cluster}")

            _search_betas(pool,
                          cluster_routes,
                          cost_attributes,
                          alphas,
                          betas,
                          real_means,
                          results_subdir,
                          iterations,
                          verbose)

    pool.close()
    pool.join()


def add_edge_attributes(G: nx.MultiDiGraph, bufsize: float = 50) -> nx.MultiDiGraph:
    """
    Enrich the graph `G` by adding edge attributes related to nearby land
    features and POIs. The `bufsize` parameter determines the distance
    (in meters) around each feature in which edges are considered nearby.

    Parameters
    ----------
    G : nx.MultiDiGraph
        The osmnx graph to be enriched.
    bufsize : float, optional
        Buffer radius in meters around each land feature or POI within which
        edges are considered nearby. Defaults to 50.

    Returns
    -------
    G_enriched : nx.MultiDiGraph
        The enriched osmnx graph.
    """

    poi_stop_flow = {
        'restaurant': ('long', 'medium'),
        'cafe': ('medium', 'high'),
        'bar': ('medium', 'high'),
        'fast_food': ('short', 'high'),
        'school': ('short', 'high'),
        'prep_school': ('short', 'low'),
        'bank': ('long', 'medium'),
        'atm': ('short', 'medium'),
        'pharmacy': ('short', 'medium'),
        'place_of_worship': ('long', 'medium'),
        'fuel': ('short', 'high'),
        'kindergarten': ('short', 'high'),
        'ice_cream': ('short', 'high'),
        'pub': ('medium', 'medium'),
        'post_office': ('medium', 'medium'),
        'parcel_locker': ('short', 'low'),
        'community_centre': ('long', 'medium'),
        'dentist': ('long', 'low'),
        'doctors': ('long', 'low'),
        'library': ('medium', 'low'),
        'veterinary': ('long', 'low'),
        'theatre': ('long', 'medium'),
        'arts_centre': ('long', 'low'),
        'events_venue': ('long', 'medium'),
        'clinic': ('long', 'medium'),
        'hospital': ('long', 'high'),
        'townhall': ('medium', 'low'),
        'cinema': ('long', 'medium'),
        'university': ('short', 'high'),
        'college': ('short', 'high'),
        'parking': ('long', 'high'),
        'charging_station': ('long', 'low'),
        'bus_station': ('short', 'high'),
        'marketplace': ('medium', 'medium'),
        'supermarket': ('medium', 'high'),
        'department_store': ('long', 'high'),
        'mall': ('long', 'high')
    }
    G = ox.add_edge_speeds(G)
    G = ox.add_edge_travel_times(G)

    nodes, edges = ox.graph_to_gdfs(G)
    envelope_coords = edges.union_all().envelope.exterior.xy
    bbox = np.array([
        envelope_coords[0][0],
        envelope_coords[1][1],
        envelope_coords[0][1],
        envelope_coords[1][2]
    ])

    # Download landuse features + shop-type amenities
    tags = {
        'amenity': list(poi_stop_flow.keys()),
        'shop': ['mall', 'supermarket', 'department_store'],
        'landuse': ['recreation_ground', 'greenery', 'grass', 'commercial', 'residential', 'industrial'],
        'water': True,
    }
    features = ox.features_from_bbox(bbox, tags).reset_index(drop=True)
    features = features.to_crs(epsg=3857) # Change crs to one that allows for area calculations in m^2

    # Store shops as amenities
    features.loc[features['shop'].notnull(), 'amenity'] = features[features['shop'].notnull()]['shop']

    # Adding POI stop and flow attributes
    features['stop_short'] = features['amenity'].map(lambda x: 1 if x in poi_stop_flow and poi_stop_flow[x][0]=='short'else 0)
    features['stop_medium'] = features['amenity'].map(lambda x: 1 if x in poi_stop_flow and poi_stop_flow[x][0]=='medium'else 0)
    features['stop_long'] = features['amenity'].map(lambda x: 1 if x in poi_stop_flow and poi_stop_flow[x][0]=='long'else 0)

    features['flow_low'] = features['amenity'].map(lambda x: 1 if x in poi_stop_flow and poi_stop_flow[x][1]=='low' else 0)
    features['flow_medium'] = features['amenity'].map(lambda x: 1 if x in poi_stop_flow and poi_stop_flow[x][1]=='medium'else 0)
    features['flow_high'] = features['amenity'].map(lambda x: 1 if x in poi_stop_flow and poi_stop_flow[x][1]=='high'else 0)

    # Add landuse area (in m^2)
    features['landuse_area'] = features[features['landuse'].isin(tags['landuse'])]['geometry'].area

    # Add water area (in m^2)
    features['water_area'] = features[features['water'].notnull()]['geometry'].area

    buffers = gpd.GeoDataFrame(
        data=features[list(tags.keys()) + [
            'landuse_area',
            'water_area',
            'stop_short', 'stop_medium', 'stop_long',
            'flow_low', 'flow_medium', 'flow_high'
        ]],
        geometry=features['geometry'].buffer(bufsize)
    )
    edges = gpd.sjoin(edges.to_crs(epsg=3857), buffers, how='left', predicate='intersects')
    
    # Replace stop and flow columns with counts
    edges['stop_short'] = edges.groupby(['u','v','key'])['stop_short'].sum()
    edges['stop_medium'] = edges.groupby(['u','v','key'])['stop_medium'].sum()
    edges['stop_long'] = edges.groupby(['u','v','key'])['stop_long'].sum()

    edges['flow_low'] = edges.groupby(['u','v','key'])['flow_low'].sum()
    edges['flow_medium'] = edges.groupby(['u','v','key'])['flow_medium'].sum()
    edges['flow_high'] = edges.groupby(['u','v','key'])['flow_high'].sum()

    # Add landuse importance for each category (log of 1 + sum of areas)
    edges['landuse_green'] = np.log1p(edges[edges['landuse'].isin(['recreation_ground', 'greenery', 'grass'])].groupby(['u','v','key'])['landuse_area'].sum())
    edges['landuse_commercial'] = np.log1p(edges[edges['landuse']=='commercial'].groupby(['u','v','key'])['landuse_area'].sum())
    edges['landuse_residential'] = np.log1p(edges[edges['landuse']=='residential'].groupby(['u','v','key'])['landuse_area'].sum())
    edges['landuse_industrial'] = np.log1p(edges[edges['landuse']=='industrial'].groupby(['u','v','key'])['landuse_area'].sum())

    # Add water importance (log of 1 + sum of areas)
    edges['water'] = np.log1p(edges.groupby(['u','v','key'])['water_area'].sum())

    edges.fillna({'landuse_green': 0,
                'landuse_commercial': 0,
                'landuse_residential': 0,
                'landuse_industrial': 0,
                'water': 0,},
                inplace=True)

    edges.drop(columns=['amenity',
                        'shop',
                        'landuse',
                        'water_area',
                        'landuse_area'], inplace=True)

    edges = edges.loc[~edges.index.duplicated(keep='first'), :]
    edges.drop_duplicates(inplace=True)

    # Transforming the highway column into residential/motorway
    edges['residential'] = edges['highway'].apply(lambda x: 1 if x in ['residential', 'living_street', 'unclassified']else 0)
    edges['motorway'] = edges['highway'].apply(lambda x: 1 if x in ['motorway', 'trunk', 'primary', 'secondary',
                                                                    'tertiary', 'motorway_link', 'trunk_link',
                                                                    'primary_link', 'secondary_link', 'tertiary_link'] else 0)
    edges.drop(columns=['highway'], inplace=True)
    
    G_enriched = ox.graph_from_gdfs(nodes, edges.to_crs(epsg=4326))

    return G_enriched
